### PR TITLE
Support gameplay with no bots

### LINKED ISSUE #95: Support gameplay without bots
## :warning: Is your feature request related to a problem? Please describe
Due to the nature of Halma, which is originally several players surround a board and play, this should be appropriate.

## :bulb: Describe the solution you'd like
We can allow the bot number to be zero. Adding a `bots` switch could be helpful too.

## :raising_hand: Do you want to develop this feature yourself?
- [x] Yes

### PR DESCRIPTION
**Pull request by CloneWith**
This PR allows gameplay with more than one human and no bots. Just a small change.

Fix #95

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
This doesn't seem to work.

**Comment by CloneWith** [comment]
Thanks for telling me that. I'll double check this when possible.

**Comment by CloneWith** [comment]
> This doesn't seem to work.

I didn't get this.
*Only* when the number of human players is set to more than 2, then we allow the number of bots to set to zero. See this picture:

image

**Comment by CrazyMarvin** [comment]
> > This doesn't seem to work.
> 
> I didn't get this.
> *Only* when the number of human players is set to more than 2, then we allow the number of bots to set to zero. See this picture:
> 
> image
> 

I'll merge this and have a closer look later.
Thanks for your support. 👍

**Pull request merged**
