### PR TITLE
Regenerate the project for libGDX 1.11.0

### PR DESCRIPTION
**Pull request by Frosty-J**
This is a complete regeneration of the project, to take us to libGDX 1.11.0 but also make some other changes. Anything not listed below might be a mistake. I suggest highlighting anything you may disagree with - the package name change is probably the most controversial.

## Removals

* Box2D. I don't see why this game would need a physics engine, but we can add it back if it does.
* Tween Engine. It's old, not really used anymore, and didn't seem to be doing anything in this. libGDX has interpolation and Scene2D actions that can be used without any need for it.
* `ios/` as there's no plans for this app to support it at present. It wouldn't be terribly difficult to return the iOS module if it's later needed.
* `game_builds/`. The build was outdated and builds belong in the releases tab or anywhere but version control.
* `.vscode/`, `android/local.properties` and a couple spurious `META-INF`s, as these probably don't belong in version control.
* `file.jks` and `newfile.jks`. Presumably one of these was used for the APK signing? While I suppose it's not a big deal if a strong password was chosen, it's bad practice to have the keystore in a public repository. These will remain in the history unless you rewrite it, which probably isn't worth doing for this.
* `packer-all.jar` and `my-packr-config.json`. #8 mentions Windows/macOS/Linux support isn't needed, and Packr could be downloaded in a GitHub Action or something anyway.
* Support for armeabi devices. libGDX dropped support for them in 1.10.0. Those devices died out along with Android 2.3 Gingerbead.

## Changes

* Increased `sourceCompatibility` from Java 7 to 8. I see no reason to keep Java 7 support.
* Changed the package name from `rocks.poopjournal.halma` to `app.halma`. This seems more professional (even if `halma.app` currently doesn't go anywhere) and avoids issues if Mr Poop Journal one day transfers ownership to Mr Zuckerberg. This change would mean existing Android installations of the app can't be updated (it would be installed as a new app instead) but judging by the low interest in this repository and the broken F-Droid etc. links I doubt that's a big deal. Still, I can easily enough change it back or even to something else.
* Disabled the accelerometer and audio, since we're currently using neither. Remember to change this in the launchers if adding sound effects.
* Centred the Play Store icon.
* Redid the Android icons with transparency, removing the oversized drawables. If @mmelnizky has a version of the icon with a transparent background, that would have cleaner results than me removing it myself, but fortunately it's such a high resolution that it becomes impossible to tell someone's fuzzy-selected it away.
* The desktop backend now uses LWJGL3, which requires Java 8.
* Gradle and the Android Gradle Plugin have been updated. Due to the latter, Java 11 or higher is required to build for Android.

## Additions

* Created `assets-raw/`, where high-quality versions of assets that aren't to be shipped with the game can live. Though some degree of caution should be taken to avoid bloating the repository size too much. It feels completely superfluous with only a couple files inside, but hopefully we'll have more one day.
* Web builds now work! (`html:superDev`) As on every other platform, it doesn't resize properly since we're still on the old core code. I removed some `StackOverflowError` catches to get it to compile, so hopefully those were no longer needed.

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Wow, this is fantastic! 👍

- **Removals:** 
  - I don't know much about libGDX but your explanations sound very reasonable.
- **Changes:** 
  - I own [poopjournal.rocks](https://poopjournal.rocks/) longer than [halma.app](https://halma.app/) so I told Martin to use this for the package name. The domain will stay with me unless Mr. Zuckerberg sends a really good offer, don't worry. 😂
But when the Halma game will be running on [halma.app](https://halma.app/) using `app.halma` as package name directly shows that they belong together. Also, `poopjournal.rocks.halma` might be a bit confusing for new players. 🤔
As the game is not published for the public yet, changing the package name is not a big issue. The release on F-Droid and Google Play is planned for the near future and no users would be affected. So let's go with your proposal. 👌
  - Maybe [this](https://raw.githubusercontent.com/Crazy-Marvin/media/master/Halma/Logo/ic_foreground.png) graphic could be the one you are looking for. Otherwise you could go to the [Figma](https://www.figma.com/file/mqDIn1vTFZ7Gas8ioM0ngJ/Halma?node-id=0%3A1) from #7 and download it. Let me know if this is not working.
  - In the _About_ screen Martin mentioned myself as lead developer. That's not really fitting because I did not contribute much code. You may switch that please and add yourself too. 
- **Additions**: 
  - I am fine with an `assets-raw` folder. I use   [this repo](https://github.com/Crazy-Marvin/media/tree/master/Halma) for graphics and other assets but to have the graphics directly in this repo might be handy. Bigger files, like a trailer for the game, should definitely be placed in the `media` repository. [Git Large File Storage](https://git-lfs.github.com/) is enabled there.
  - Web builds are awesome. I think when the game is running in the browser, installers for the desktop operating systems are not that useful as mentioned in #8 and they would increase the complexity of the project. Do you agree or do you recommend to have desktop installers?
  - As next step, we might discuss how to host the game. We can do so in #8.

Thank you so much! 🙏

**Comment by Frosty-J** [comment]
> Maybe [this](https://raw.githubusercontent.com/Crazy-Marvin/media/master/Halma/Logo/ic_foreground.png) graphic could be the one you are looking for.

Ah, so this is the intended app icon? Is there a higher-resolution/SVG version of it available? This is probably good enough, though - haven't investigated.

> In the _About_ screen Martin mentioned myself as lead developer.

So make Martin lead developer and yourself co-developer, or...? Maybe you could be the director or something.

> I think when the game is running in the browser, installers for the desktop operating systems are not that useful

I agree. I don't think it would be too difficult to set up, but I don't really see the point when someone will be able to just go to the web address. And I like how, with web versions, all users will always be on the latest version. There are some limitations with libGDX's web support, but nothing too important for this. One limitation is non-continuous rendering isn't supported, meaning the game will be rendering 60 times a second (or whatever the user's refresh rate is) whether you want to or not, which could drain laptop batteries if staring at a board. I don't know why that limitation exists - it's on my to-do list to look at, but a long way down.

**Comment by CrazyMarvin** [comment]
> So make Martin lead developer and yourself co-developer, or...? Maybe you could be the director or something.

Good idea , make me the director and put Martin and yourself as lead developers. 👍

**Comment by CrazyMarvin** [comment]
I will already merge this now but feel very welcome to make another PR with your ideas later. 🙏

**Pull request merged**
